CREATE TABLE IF NOT EXISTS UserTypes (
    UserTypeId INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    UserTypeName VARCHAR(16) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Users (
    UserId INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Username VARCHAR(256) NOT NULL UNIQUE,
    HashedPassword VARCHAR(512) NOT NULL,
    UserTypeId INTEGER NOT NULL,
    FOREIGN KEY (UserTypeId) REFERENCES UserTypes(UserTypeId)
);

CREATE TABLE IF NOT EXISTS Products (
    ProductId INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ProductName VARCHAR(256) NOT NULL UNIQUE,
    ProductDescription VARCHAR(1024) NOT NULL,
    ProductImageBase64 VARCHAR(1048576),
    ProductPricePence INTEGER NOT NULL
);


CREATE TABLE IF NOT EXISTS UserContactDetails (
    UserContactDetailsId INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    UserId INTEGER NOT NULL,
    AddressLine1 VARCHAR(256) NOT NULL,
    AddressLine2 VARCHAR(256),
    TownCity VARCHAR(256) NOT NULL,
    County VARCHAR(256) NOT NULL,
    Postcode VARCHAR(8) NOT NULL,
    PhoneNumber VARCHAR(16),
    Email VARCHAR(512) NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(UserId)
);

CREATE TABLE IF NOT EXISTS Invoices (
    InvoiceId INTEGER PRIMARY KEY AUTO_INCREMENT,
    InvoiceValuePence INTEGER NOT NULL,
    DateTimeCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UserContactDetailsId INTEGER NOT NULL,
    FOREIGN KEY (UserContactDetailsId) REFERENCES UserContactDetails(UserContactDetailsId)
);

CREATE TABLE IF NOT EXISTS InvoiceDetails (
    InvoiceDetailsId INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    InvoiceId INTEGER NOT NULL,
    ProductId INTEGER NOT NULL,
    Quantity INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (InvoiceId) REFERENCES Invoices(InvoiceId),
    FOREIGN KEY (ProductId) REFERENCES Products(ProductId)
);